version: '3'
services:
  blue:
    container_name: blue
    image: kingzzangssang/blue-green
    expose:
      - 8080
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul
  green:
    container_name: green
    image: kingzzangssang/blue-green
    expose:
      - 8080
    ports:
      - 8082:8080
    environment:
      - TZ=Asia/Seoul
